# Generated by Django 4.2 on 2023-06-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0013_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='productId',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ecomm.product'),
            preserve_default=False,
        ),
    ]
