# Generated by Django 4.2 on 2023-06-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0017_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_day',
            field=models.IntegerField(default=0),
        ),
    ]
