# Generated by Django 4.2 on 2023-06-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0019_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='black', max_length=100),
            preserve_default=False,
        ),
    ]
