# Generated by Django 4.2 on 2023-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='image',
            new_name='imageUrl',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='unitPrice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='description',
        ),
        migrations.RemoveField(
            model_name='order',
            name='popularity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rating',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
