# Generated by Django 4.2 on 2023-06-22 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0011_alter_myuser_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='password_reset_token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
