# Generated by Django 4.2 on 2023-06-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0015_rename_file_review_media_remove_review_preview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='product_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
